### ISSUE TITLE
May I ask which GPU the model is inferenced on, thank you

### ISSUE THREAD

**Issue by weishuai-GitHub** [Sierkinhane/BoxDiff#4]

**Comment by Sierkinhane** [comment]
Hi, we did the experiments on Tesla V100(32G).

**Comment by weishuai-GitHub** [comment]
Thank you. Your work is very nice.

**Comment by Sierkinhane** [comment]
Thanks :)

**Comment by Z-MU-Z** [comment]
Hi , I encounter cuda out of memory, when i run python3 run_gligen_boxdiff.py --prompt "A rabbit wearing sunglasses looks very proud" --gligen_phrases ["a rabbit","sunglasses"] --P 0.2 --L 1 --seeds [1,2,3,4,5,6,7,8,9] --token_indices [2,4] --bbox [[67,87,366,512],[66,130,364,262]] --refine False. I use 4090(24G) ,  is that normal and how to fix it?

**Comment by Sierkinhane** [comment]
Hi, when I run `run_gligen_box.py` on Tesla V100 (32GB) with PyTorch (1.12.0), it takes about 20 GB memory. May I know your PyTorch version?

**Comment by Z-MU-Z** [comment]
I use torch              1.10.1

**Comment by Sierkinhane** [comment]
Maybe you can try to upgrade PyTorch :)

**Comment by Z-MU-Z** [comment]
Thanks! I will try it later

**Comment by Z-MU-Z** [comment]
After I upgraded torch from 1.10 to 1.12, the problem was solved

**Comment by Sierkinhane** [comment]
Got it!
